app/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from app.core import views


app_name = 'core'

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name="robots.txt",
                                            content_type="text/plain")),
    path('s', views.search),
    path('contact/', views.contact, name='contact'),
    path('set_timezone/', views.set_timezone, name='timezone'),
    path('about/', views.About.as_view(), name='about'),
    path('random-thread/', views.random_thread, name='random'),
]

app/entries/urls.py
from django.urls import path

from app.entries import views


app_name = 'entry'

urlpatterns = [
    path('<int:pk>/', views.EntryRead.as_view(), name='read'),
    path('edit/<int:pk>/', views.EntryUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', views.EntryDelete.as_view(), name='delete'),

    path('t/<slug>/entry', views.add_entry, name='create'),
    path('favorite/<int:pk>/', views.favorite_entry, name='favorite'),
]

app/threads/urls.py
from django.urls import path

from app.threads import views
from . import views, admin

app_name = 'thread'

urlpatterns = [
    path('', views.index, name='idx'),
    path('threads/', views.ThreadIndex.as_view(), name='index'),
    # path('threads/create/', views.ThreadCreate.as_view(), name='create-thread'),
    path('t/<slug>/', views.ThreadRead.as_view(), name='read'),
    # path('tu/<int:id>/', views.short_thread_read, name='short-read'),
    path('thread/new/', views.newt, name='new'),
    path('tags/', views.TagIndex.as_view(), name='tags'),
    path('tag/<slug>/', views.TagRead.as_view(), name='tag-read'),
    path('nav_tag_factory/<str:lang>', views.nav_tag_factory),
]

app/users/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'user'

urlpatterns = [
    # path('enter/', auth_views.LoginView.
    #      as_view(template_name='auth/login.html'), name='login'),
    path('enter/', views.Login.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('ajax/validate_username', views.validate_username,
         name='validate_username'),
    path('@<username>/', views.Profile.as_view(), name='profile'),
    path('@<username>/favorites/', views.Favorites.as_view(), name='favorites'),

    path('change-pass/', views.PasswordChange.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),

    path('reset-pass/', views.PasswordReset.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

# from app.core.views import redirect_search
from app.core.sitemaps import EASitemap

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('h2pj8mnv3z/', admin.site.urls),
    path('entry/', include('app.entries.urls')),
    path('', include('app.threads.urls')),
    path('', include('app.users.urls')),
    path('', include('app.core.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {"sitemap": EASitemap}},
         name='django.contrib.sitemaps.views.sitemap')

    # path('<str:string>', redirect_search),
    # path('', include('django.contrib.auth.urls')),
]

# Django Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
    ] + urlpatterns

app/entries/models.py
import re
from typing import Any, Union

import bleach

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F, Count, Q, OuterRef
from django.http import request
from django.urls import reverse
from django.utils import timezone
from django.utils.text import Truncator

from app.core.models import SoftDeletionModel, SoftDeletionManager
from app.threads.models import Thread
from . managers import EntryManager


class Entry(SoftDeletionModel):
    body = models.TextField()
    first_body = models.TextField(null=True, blank=True)  # if entry edited keep first body
    lang = models.CharField(choices=settings.LANGUAGES, max_length=2)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='entries')
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE,
                               related_name='entries')
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(blank=True, null=True)

    objects = EntryManager()

    class Meta:
        verbose_name_plural = 'entries'
        indexes = [
            models.Index(fields=['created_at']),
        ]
        ordering = ['created_at']

    def __str__(self):
        truncated_entry = Truncator(self.body)
        return str(truncated_entry.chars(30))
        # return str(self.id)

    def get_absolute_url(self):
        return reverse('entry:read', args=[self.id])

    def get_body(self):
        p = re.compile(r"\(((?:see:|bkz:|aka:)) ([\w \W]{0,64}?)\)")
        entry = re.sub(p, r"(\1 <a href='/s?q=\2'>\2</a>)", self.body)
        # \((bkz:|see:|aka:) (\w[\w ]{0,50})\) ->p
        # ($1 <a href="/s?q=$2>$2</a>") -> entry
        # p = re.compile(r"\((?:bkz:|see:) (\w[\w ]{0,50})\)")
        # entry = re.sub(p, r'(\1 <a href="/s?q=\1>\1</a>")', self.body)

        return bleach.clean(entry)
        # return mark_safe(self.body)
        # return mark_safe(markdown(self.body, safe_mode='escape'))
        # return markdown(self.body, safe_mode='escape')

    def get_next(self):
        """ Get the next entries count in the thread, used in entry read """
        return Entry.objects.filter(thread=self.thread). \
            filter(created_at__gt=self.created_at).count()

    def get_previous(self):
        """ Get the previous entries count in the thread """
        return Entry.objects.filter(thread=self.thread). \
            filter(created_at__lt=self.created_at).count()

    def get_favorites(self):
        return self.favorites.all()

    def is_faved(self, user_id):
        if user_id in self.favorites.all():
            return True


class Favorite(models.Model):
    id = None
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='favorites')
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE,
                              related_name='favorites')

    class Meta:
        unique_together = ('user', 'entry')

# class Like(models.Model):
#     pass

app/entries/forms.py
import bleach

from django import forms

from .models import Entry


class EntryForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(
        attrs={'required': "true", 'cols': "75%", 'rows': "5",
               "id": "entryarea", "spellcheck": "false", "class": "textarea"}),
        max_length=50000, required=True, label='')

    class Meta:
        model = Entry
        fields = ['body']


class BodyForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'your ea', 'cols': "75%", 'rows': "5"}),
        max_length=50000, required=True, label='')

    def clean_body(self):
        data = self.cleaned_data['body'].lower()
        # r = bleach.clean(data, tags=['a'], attributes={}, styles=[])
        return data

app/entries/views.py
import json
import time

import bleach
from bleach.sanitizer import ALLOWED_TAGS, ALLOWED_ATTRIBUTES, ALLOWED_STYLES
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F, QuerySet
from django.http import Http404, HttpResponseNotFound, HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import get_language as lang
from django.utils.translation import ugettext as _
from django.views import generic

from .forms import EntryForm, BodyForm
from .models import Entry, Favorite
from ..threads.models import Thread


class EntryRead(generic.DetailView):
    model = Entry
    template_name = 'entries/read.html'

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        queryset = self.get_queryset().with_favs(self.request.user)\
            .annotate(username=F("user__username")).select_related("thread")
        try:
            entry = queryset.get(pk=pk)
        except ObjectDoesNotExist:
            entry = None
        return entry

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id'] = self.kwargs['pk']
        # context['tags'] = self.get_object().thread.tags.all
        return context


class EntryUpdate(generic.UpdateView):
    model = Entry
    template_name = 'entries/update.html'
    form_class = EntryForm

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if not obj.updated_at:
            obj.first_body = obj.body
            obj.save()

        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.body = bleach.clean(entry.body, tags=[])
        entry.updated_at = timezone.now()
        entry.save()
        messages.success(self.request, message=_("your entry was updated successfully"))
        return redirect('entry:read', pk=entry.pk)

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            messages.error(request, message=_("what a nice entry isn't it? if is not try to complain."))
            return redirect(obj.thread)
        return super(EntryUpdate, self).dispatch(request, *args, **kwargs)


class EntryDelete(generic.DeleteView):
    model = Entry
    context_object_name = 'entry'
    template_name = 'entries/confirm_delete.html'
    success_url = '/'

    def get_object(self, queryset=None):
        return self.entry

    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg)
        queryset = self.get_queryset().annotate(username=F("user__username")) \
            .select_related('thread')
        try:
            self.entry = queryset.get(id=pk)
        except ObjectDoesNotExist:
            return redirect("entry:read", pk)

        if self.entry.user_id != self.request.user.id:
            messages.error(request, _("this entry is not your. don't even try"))
            return redirect("entry:read", pk)
        return super(EntryDelete, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        thread = self.entry.thread
        self.entry.delete()
        messages.info(request, _("your entry was deleted successfully"))
        return redirect(thread)


@login_required
def add_entry(request, slug):
    thread = get_object_or_404(Thread, slug=slug)
    if thread.is_closed:
        messages.error(request, _("this thread is closed don't even try"))
        return redirect(thread)
    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.body = bleach.clean(entry.body, tags=[])
            entry.thread = thread
            entry.user = request.user  # auth.get_user(request)
            entry.lang = thread.lang   # lang() langs should be same as thread
            entry.created_at = timezone.now()  # removed auto_now_add for adm
            entry.save()

            thread.last_entry = timezone.now()
            thread.save()

            thread_url = reverse('thread:read', kwargs={'slug': slug})
            url = f'{thread_url}?page=last#{entry.id}'
            messages.success(request, _('your entry was published'))
            return redirect(url)
    return redirect(thread)


@login_required
def favorite_entry(request, pk):
    favorite, created = Favorite.objects\
        .get_or_create(user=request.user, entry=Entry.objects.get(id=pk))
    # time.sleep(0.1)
    if not created:
        favorite.delete()

    return HttpResponse(
        json.dumps({
            "result": created,
            "count": Favorite.objects.filter(entry_id=pk).count()
        }),
        content_type="application/json")

templates/app/about.html
{% extends "app/base.html" %}{% load i18n %}{% get_current_language as LANGUAGE %}
{% block title_wrapper %}
  <title>about entry area - {% trans "eager society" %}</title>
{% endblock %}

{% block content %}
  <p class="title">entry area</p>
  <br>
  {% if LANGUAGE == "en" %}
  {% elif LANGUAGE == "tr" %}
  {% endif %}
{% endblock %}

templates/app/base.html
<!DOCTYPE html>{% load static %}{% load i18n %}{% get_current_language as LANGUAGE %}
<html lang="{{ LANGUAGE }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="entry area - eager society">
  <meta name="theme-color" content="#222222">

  <meta property="og:title" content="entry area">
  <meta property="og:site_name" content="entryarea">
  <meta property="og:url" content="https://entryarea.com/">
  <meta property="og:description" content="">
  <meta property="og:type" content="article">
  <meta property="og:image" content="https://entryarea.com/static/img/min.svg">
  <meta name="yandex-verification" content="94d4d44409c0b34b"/>
  <meta name="msvalidate.01" content="08EBA8CFCC2960FC3CC8AE7ECE55241C"/>

  <link rel="canonical" href="https://entryarea.com/"/>


  <link rel="apple-touch-icon" sizes="180x180" href="{% static "img/favi/apple-touch-icon.png" %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/favi/favicon-32x32.png" %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/favi/favicon-16x16.png" %}">
  <link rel="manifest" href="{% static "img/favi/site.webmanifest" %}">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143054677-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-143054677-1');
  </script>

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-WMQK68W');</script>
  <!-- End Google Tag Manager -->


  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/style.min.css" %}">
  <link disabled id="site-light" rel="stylesheet" href="{% static "css/style-light.min.css" %}">
  {% block title_wrapper %}<title>{% block title %}{% endblock %}entry area</title>{% endblock %}
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  {% include "partial/svg.html" %}
</svg>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WMQK68W"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<header>
  {% include "partial/header.html" %}
</header>
<div class="main main-content">
  <section class="columns">
    <aside id="lefting" class="column is-3 is-narrow-mobile is-hidden-mobile">
      {% include "app/leftpane.html" %}
    </aside>
    <div class="column is-6 is-12-mobile p-20">
      {% block content %}{% endblock %}
    </div>
    <aside class="column is-3">
      {% block rightpane %}{% endblock %}
    </aside>
  </section>
  <footer class="footer column is-offset-3">
    {% include "app/footer.html" %}
  </footer>
</div>
<div name="fix-com">
  {% include "partial/lang-switcher.html" %}
  {% include "partial/message.html" %}
</div>
<script>
  function theme_toggle() {
    var el1 = document.getElementById("site-light");
    if (el1.disabled) {
      el1.disabled = false;
      localStorage.setItem("theme", "light");
    } else {
      el1.disabled = true;
      localStorage.setItem("theme", "dark");
    }
  }

  if (localStorage.getItem("theme") === "light") {
    document.getElementById("site-light").disabled = false;
  } else {
    document.getElementById("site-light").disabled = true;
  }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"
        integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
{#<script src="{% static "js/jquery.js" %}"></script>#}
{#<script src="{% static "js/jquery-ui.js" %}"></script>#}
<script src="{% static "js/readmore.min.js" %}"></script>
<script>
  $(".entry-content").readmore({
    moreLink: '<a href="#"><b>{% trans "read more..." %}</b></a>',
    lessLink: '',
    collapsedHeight: 198
  });
</script>
<script src="{% static "js/base.js" %}"></script>
{% block script %}{% endblock %}
</body>
</html>

templates/app/contact.html
{% extends 'app/base.html' %}{% load i18n %}{% load widget_tweaks %}
{% block title %}
  {% trans "contact" %} -
{% endblock %}
{% block content %}
  <p class="title is-3">{% trans "contact us" %}</p>
  <form method="post">
    {% csrf_token %}
    <div class="field">
      <div class="control">
        <div class="label">
          {% trans "email" %}:
          <div class="help is-pulled-right">
            {% trans "not required. if you want response." %}
          </div>
        </div>
        {% render_field form.email class="input" %}
      </div>
    </div>
    <br>
    <div class="field">
      <div class="control">
        <div class="label">
          {% trans "subject" %}:
        </div>
        {% render_field form.subject class="input" %}
      </div>
    </div>
    <div class="field">
      <div class="control">
        <div class="label">
          {% trans "message" %}:
        </div>
        {% render_field form.message class="textarea" %}
      </div>
    </div>
    <div class="field">
      <div class="control">
        <button class="button is-primary is-rounded">
          {% trans "send" %}
        </button>
      </div>
    </div>
  </form>
{% endblock %}

{% block rightpane %}
  <p class="subtitle">email:</p>
  <p class="is-size-7">entryarea (at) gmail [dot] com</p>
{% endblock %}

templates/app/entry.html
<div class="entry">{% load i18n %}{% load tz %}
  <div id="{{ entry.id }}" class="pointer"></div>
  <div class="entry-content">
    {% autoescape off %}
      {{ entry.get_body | linebreaksbr | lower }}
    {% endautoescape %}
  </div>
  <div class="level is-mobile">
    <div class="level-left">
      <div class="level-item">
        <span class="is-size-7" style="margin-right: 10px">
          <a href="{% url "entry:read" entry.id %}">#{{ entry.id }}</a>
        </span>
        <a class="favorite {{ entry.is_faved }}" data-count="{{ entry.fav_cnt }}"
           {% if user.is_authenticated %}data-action="fav"{% endif %} data-id="{{ entry.id }}">
          <svg class="fav-icon">
            <use xlink:href="#fav-icon"></use>
          </svg>
        </a>
        <span class="is-size-7 fav-cnt" style="margin-left: 5px">
          {% ifnotequal entry.fav_cnt 0 %}
            <a href="#">{{ entry.fav_cnt }}</a>
          {% endifnotequal %}
        </span>
      </div>
    </div>
    <div class="">
      <div class="level is-mobile" style="flex-wrap: wrap">
        <div class="level-left is-marginless">
          <div class="level-item">
            <span class="is-size-7">{% localtime on %}
              <a href="{% url "entry:read" entry.id %}">{% spaceless %}
                {{ entry.created_at|date:"d.m.Y · H:i" }}
                {% if entry.updated_at %}
                  {% if entry.created_at|date:"d.m.Y" == entry.updated_at|date:"d.m.Y" %}
                    ~ {{ entry.updated_at|date:"H:i" }}
                  {% elif entry.created_at|date:"Y" == entry.updated_at|date:"Y" %}
                    ~ {{ entry.updated_at|date:"d.m · H:i" }}
                  {% else %}
                    {{ entry.updated_at|date:"d.m.Y · H:i" }}
                  {% endif %}
                {% endif %}{% endspaceless %}
              </a>{% endlocaltime %}
            </span>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <a href="{% url "user:profile" entry.username %}" class="nick">{{ entry.username }}</a>
            <div class="dropdown is-hoverable is-right">
              <div class="dropdown-menu" id="dropdown-menu" role="menu">
                <div class="dropdown-content">
                  {% if request.user.is_staff %}
                    <a href="{% url "admin:index" %}entries/entry/{{ entry.id }}"
                       class="dropdown-item">{% trans "edit on admin" %}</a>
                  {% endif %}
                  {% ifequal request.user.username entry.username %}
                    <a href="{% url "entry:delete" entry.id %}" class="dropdown-item">{% trans "delete" %}</a>
                    <a href="{% url "entry:update" entry.id %}" class="dropdown-item">{% trans "edit" %}</a>
                  {% else %}
                    <a href="{% url "core:contact" %}?subject={% trans "complain" %} entry %23{{ entry.id }}"
                       class="dropdown-item">{% trans "complain" %}</a>
                  {% endifequal %}
                </div>
              </div>
              <div class="dropdown-trigger">
                <svg class="dots-icon">
                  <use xlink:href="#dots-icon"></use>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/app/entryarea.html
{% if user.is_authenticated %}{% load i18n %}
  {% if not thread.is_closed %}
    <form action="{% spaceless %}
      {% if thread %}
        {% url "entry:create" thread.slug %}
      {% else %}
        {% url "thread:new" %}
      {% endif %}{% endspaceless %}" method="post" id="ea">{% csrf_token %}
      <div class="field">
        <div class="control">
          {% if not thread %}
            {{ tform.as_p }}
            {{ eform.as_p }}
          {% else %}
            {{ form.as_p }}
          {% endif %}
        </div>
      </div>
      <div class="field">
        <div class="control">
          <button name="save" class="button is-primary is-outlined is-rounded" type="submit">{% trans "send" %}</button>
        </div>
      </div>
    </form>
  {% else %}
    {% trans "thread is closed." %}
  {% endif %}
{% else %}
  <p class="entry">{% trans "please" %}
    <a href="{% url 'user:login' %}?next={{ request.get_full_path }}" class="primary">{% trans "enter" %}</a>
    {% trans "to write" %}
  </p>
{% endif %}

templates/app/footer.html
<div class="level is-mobile" style="flex-wrap: wrap">{% load i18n %}
  <div class="level-item">
    <a href="{% url "core:contact" %}">{% trans "contact" %}</a>
  </div>
  <div class="level-item">
    <a href="{% url "core:about" %}">{% trans "about" %}</a>
  </div>
  <div class="level-item">
    <a href="#" onclick="theme_toggle();return false;">{% trans "dark/light" %}</a>
  </div>
  <div class="level-item">
    <a href="{% url "core:timezone" %}">{% trans "set timezone" %}</a>
  </div>
  <div class="level-item">
    <a href="{% url "core:random" %}">{% trans "random thread" %}</a>
  </div>
</div>

templates/app/leftpane.html
<div class="over">{% load i18n %}
  <p class="subtitle is-4"></p>
  <ul class="menu-list">
  </ul>
{#  <a href="#" class="primary has-text-centered">{% trans "more" %}...</a>#}
</div>