app/threads/urls.py
from django.urls import path

from app.threads import views
from . import views, admin

app_name = 'thread'

urlpatterns = [
    path('', views.index, name='idx'),
    path('threads/', views.ThreadIndex.as_view(), name='index'),
    # path('threads/create/', views.ThreadCreate.as_view(), name='create-thread'),
    path('t/<slug>/', views.ThreadRead.as_view(), name='read'),
    # path('tu/<int:id>/', views.short_thread_read, name='short-read'),
    path('thread/new/', views.newt, name='new'),
    path('tags/', views.TagIndex.as_view(), name='tags'),
    path('tag/<slug>/', views.TagRead.as_view(), name='tag-read'),
    path('nav_tag_factory/<str:lang>', views.nav_tag_factory),
]

app/users/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'user'

urlpatterns = [
    # path('enter/', auth_views.LoginView.
    #      as_view(template_name='auth/login.html'), name='login'),
    path('enter/', views.Login.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('ajax/validate_username', views.validate_username,
         name='validate_username'),
    path('@<username>/', views.Profile.as_view(), name='profile'),
    path('@<username>/favorites/', views.Favorites.as_view(), name='favorites'),

    path('change-pass/', views.PasswordChange.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),

    path('reset-pass/', views.PasswordReset.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

# from app.core.views import redirect_search
from app.core.sitemaps import EASitemap

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('h2pj8mnv3z/', admin.site.urls),
    path('entry/', include('app.entries.urls')),
    path('', include('app.threads.urls')),
    path('', include('app.users.urls')),
    path('', include('app.core.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {"sitemap": EASitemap}},
         name='django.contrib.sitemaps.views.sitemap')

    # path('<str:string>', redirect_search),
    # path('', include('django.contrib.auth.urls')),
]

# Django Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
    ] + urlpatterns

templates/partial/header.html
<div class="container main">{% load i18n %}{% get_current_language as LANGUAGE %}
  <div id="topbar">
    <div class="columns is-mobile is-vcentered">
      <div class="column is-3 is-hidden-mobile">
        <a href="/" id="logo">
          {{ LANGUAGE }}
        </a>
      </div>
      <div class="column is-narrow-mobile is-hidden-tablet" style="width: 90px;padding-right: 0">
        <a href="/" id="min-logo">
          {{ LANGUAGE }}
        </a>
      </div>
      <div class="column is-6-tablet" style="padding-left: 0">
        <div class="search-container">
          <div style="width: 100%">
            <form action="/s" method="GET" role="search">
              <input id="q" type="text" placeholder="{% trans "thread, #entry or @user" %}"
                     class="search-bar" name="q" spellcheck="false" autocomplete="off"
                     maxlength="64">
              <button type="submit" class="search-btn">
                <svg class="search-icon">
                  <use xlink:href="#search-icon"></use>
                </svg>
              </button>
            </form>
          </div>
        </div>
      </div>
      <div class="column is-3 is-hidden-mobile">
        <div class="is-pulled-right">
          {% if user.is_authenticated %}
            <a href="{% url 'user:profile' user.username %}" title="{{ user.get_username }}">
              <svg class="profile-icon">
                <use xlink:href="#profile-icon"></use>
              </svg>
              {% trans "me" %}
            </a>
            <a href="{% url 'user:logout' %}?next={{ request.get_full_path }}" style="margin: 0 20px">
              <svg class="logout-icon">
                <use xlink:href="#logout-icon"></use>
              </svg>
              {% trans "logout" %}
            </a>
          {% else %}
            <a href="{% url 'user:login' %}?next={{ request.get_full_path }}"
               class="button is-primary is-outlined is-rounded is-small">
              {% trans "enter" %}
            </a>
            <a href="{% url 'user:register' %}" id="register"
               class="button is-primary is-rounded is-small">
              {% trans "register" %}
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div id="subbar">
    <div class="level is-hidden-mobile is-marginless">
      <div class="level-item">
        <a href="{% url "thread:index" %}?week=1" class="taq">{% trans "week" %}</a>
      </div>
      <div class="level-item">
        <a href="{% url "thread:index" %}" class="taq">{% trans "all" %}</a>
      </div>
      <div class="level-item">
        <a href="{% url "thread:tags" %}">{% trans "tags" %}</a></div>
      {% if LANGUAGE == "en" %}
        {% include "partial/nav/en.html" %}
      {% elif LANGUAGE == "tr" %}
        {% include "partial/nav/tr.html" %}
      {% endif %}
    </div>
  </div>
  <div id="subbar-mobile">
    <div class="is-hidden-tablet level is-mobile">
      <div class="level-item">
        <a href="{% url 'thread:index' %}?week=1">{% trans "week" %}</a>
      </div>
      <div class="level-item">
        <a href="{% url 'thread:index' %}">{% trans "all" %}</a>
      </div>
      <div class="level-item">
        <a href="{% url 'thread:tags' %}">{% trans "tags" %}</a>
      </div>
      {% if user.is_authenticated %}
        <div class="level-item">
          <a href="{% url 'user:profile' user.username %}">
{#            {% trans "me" %}#}
            <svg class="profile-icon" style="width: 18px;
						    height: 18px;">
              <use xlink:href="#profile-icon"></use>
            </svg>
          </a>
        </div>
        <div class="level-item">
          <a href="{% url 'user:logout' %}?next={{ request.get_full_path }}" class="is-primary">
{#            {% trans "logout" %}#}
            <svg class="logout-icon" style="width: 18px;
						    height: 18px;">
              <use xlink:href="#logout-icon"></use>
            </svg>
          </a>
        </div>
      {% else %}
        <div class="level-item">
          <a href="{% url 'user:login' %}?next={{ request.get_full_path }}">{% trans "enter" %}</a>
        </div>
        <div class="level-item">
          <a href="{% url 'user:register' %}" class="is-primary">{% trans "register" %}</a>
        </div>
      {% endif %}
    </div>
  </div>
</div>

templates/partial/lang-switcher.html
<div id="lang-switcher">{% load i18n %}
  <ul id="doc-languages" class="language-switcher">
    <li class="other">
      <a href="https://en.entryarea.com{{ request.get_full_path }}" title="{% trans " english" %}">en</a>
    </li>
    <li class="other">
      <a href="https://tr.entryarea.com{{ request.get_full_path }}" title="{% trans " turkish" %}">tr</a>
    </li>
    <li class="current">
      <span class="noselect">
        {% get_current_language as LANGUAGE %}
        {% trans "language" %}:
        <strong>{{ LANGUAGE }}</strong>
      </span>
    </li>
  </ul>
</div>

templates/partial/message.html
{% if messages %}
  <div id="mesaj">
    <div class="message is-primary">
      <div class="message-body">
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div>
    </div>
  </div>
{% endif %}

templates/partial/pagination.html
{% if is_paginated %}{% load pagination %}
  <div class="field">
    <div class="control">
      {% if page_obj.has_previous %}
        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">
          <button id="pag" class="button is-primary is-outlined is-small is-rounded"><</button>
        </a>
      {% endif %}
      <div class="select is-primary is-small is-rounded" style="margin: 0 3px">
        <select name="" id="paginator" class="dark-pag">
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <option selected value="{{ i }}" data-href="?{% url_replace request 'page' i %}">{{ i }}</option>
            {% else %}
              <option value="{{ i }}" data-href="?{% url_replace request 'page' i %}">{{ i }}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>
      {% if page_obj.has_next %}
        <a href="?{% url_replace request 'page' page_obj.next_page_number %}">
          <button id="pag" class="button is-primary is-outlined is-small is-rounded">></button>
        </a>
      {% endif %}
    </div>
  </div>
{% endif %}

templates/partial/svg.html
<symbol id="search-icon" viewBox="0 0 24 24">
  <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
  <path d="M0 0h24v24H0z" fill="none"/>
</symbol>
<symbol id="dots-icon" viewBox="0 0 24 24">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M6 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm12 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm-6 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/>
</symbol>
<symbol id="fav-icon" , viewBox="0 0 24 24">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
</symbol>
<symbol id="profile-icon" viewBox="0 0 24 24">
  <path fill="none" d="M0 0h24v24H0V0z"/>
  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zM7.07 18.28c.43-.9 3.05-1.78 4.93-1.78s4.51.88 4.93 1.78C15.57 19.36 13.86 20 12 20s-3.57-.64-4.93-1.72zm11.29-1.45c-1.43-1.74-4.9-2.33-6.36-2.33s-4.93.59-6.36 2.33C4.62 15.49 4 13.82 4 12c0-4.41 3.59-8 8-8s8 3.59 8 8c0 1.82-.62 3.49-1.64 4.83zM12 6c-1.94 0-3.5 1.56-3.5 3.5S10.06 13 12 13s3.5-1.56 3.5-3.5S13.94 6 12 6zm0 5c-.83 0-1.5-.67-1.5-1.5S11.17 8 12 8s1.5.67 1.5 1.5S12.83 11 12 11z"/>
</symbol>
<symbol id="logout-icon" viewBox="0 0 24 24">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M10.09 15.59L11.5 17l5-5-5-5-1.41 1.41L12.67 11H3v2h9.67l-2.58 2.59zM19 3H5c-1.11 0-2 .9-2 2v4h2V5h14v14H5v-4H3v4c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"/>
</symbol>