app/entries/urls.py
from django.urls import path

from app.entries import views


app_name = 'entry'

urlpatterns = [
    path('<int:pk>/', views.EntryRead.as_view(), name='read'),
    path('edit/<int:pk>/', views.EntryUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', views.EntryDelete.as_view(), name='delete'),

    path('t/<slug>/entry', views.add_entry, name='create'),
    path('favorite/<int:pk>/', views.favorite_entry, name='favorite'),
]

app/threads/urls.py
from django.urls import path

from app.threads import views
from . import views, admin

app_name = 'thread'

urlpatterns = [
    path('', views.index, name='idx'),
    path('threads/', views.ThreadIndex.as_view(), name='index'),
    # path('threads/create/', views.ThreadCreate.as_view(), name='create-thread'),
    path('t/<slug>/', views.ThreadRead.as_view(), name='read'),
    # path('tu/<int:id>/', views.short_thread_read, name='short-read'),
    path('thread/new/', views.newt, name='new'),
    path('tags/', views.TagIndex.as_view(), name='tags'),
    path('tag/<slug>/', views.TagRead.as_view(), name='tag-read'),
    path('nav_tag_factory/<str:lang>', views.nav_tag_factory),
]

app/users/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'user'

urlpatterns = [
    # path('enter/', auth_views.LoginView.
    #      as_view(template_name='auth/login.html'), name='login'),
    path('enter/', views.Login.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('ajax/validate_username', views.validate_username,
         name='validate_username'),
    path('@<username>/', views.Profile.as_view(), name='profile'),
    path('@<username>/favorites/', views.Favorites.as_view(), name='favorites'),

    path('change-pass/', views.PasswordChange.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),

    path('reset-pass/', views.PasswordReset.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

# from app.core.views import redirect_search
from app.core.sitemaps import EASitemap

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('h2pj8mnv3z/', admin.site.urls),
    path('entry/', include('app.entries.urls')),
    path('', include('app.threads.urls')),
    path('', include('app.users.urls')),
    path('', include('app.core.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {"sitemap": EASitemap}},
         name='django.contrib.sitemaps.views.sitemap')

    # path('<str:string>', redirect_search),
    # path('', include('django.contrib.auth.urls')),
]

# Django Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
    ] + urlpatterns

app/entries/models.py
import re
from typing import Any, Union

import bleach

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F, Count, Q, OuterRef
from django.http import request
from django.urls import reverse
from django.utils import timezone
from django.utils.text import Truncator

from app.core.models import SoftDeletionModel, SoftDeletionManager
from app.threads.models import Thread
from . managers import EntryManager


class Entry(SoftDeletionModel):
    body = models.TextField()
    first_body = models.TextField(null=True, blank=True)  # if entry edited keep first body
    lang = models.CharField(choices=settings.LANGUAGES, max_length=2)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='entries')
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE,
                               related_name='entries')
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(blank=True, null=True)

    objects = EntryManager()

    class Meta:
        verbose_name_plural = 'entries'
        indexes = [
            models.Index(fields=['created_at']),
        ]
        ordering = ['created_at']

    def __str__(self):
        truncated_entry = Truncator(self.body)
        return str(truncated_entry.chars(30))
        # return str(self.id)

    def get_absolute_url(self):
        return reverse('entry:read', args=[self.id])

    def get_body(self):
        p = re.compile(r"\(((?:see:|bkz:|aka:)) ([\w \W]{0,64}?)\)")
        entry = re.sub(p, r"(\1 <a href='/s?q=\2'>\2</a>)", self.body)
        # \((bkz:|see:|aka:) (\w[\w ]{0,50})\) ->p
        # ($1 <a href="/s?q=$2>$2</a>") -> entry
        # p = re.compile(r"\((?:bkz:|see:) (\w[\w ]{0,50})\)")
        # entry = re.sub(p, r'(\1 <a href="/s?q=\1>\1</a>")', self.body)

        return bleach.clean(entry)
        # return mark_safe(self.body)
        # return mark_safe(markdown(self.body, safe_mode='escape'))
        # return markdown(self.body, safe_mode='escape')

    def get_next(self):
        """ Get the next entries count in the thread, used in entry read """
        return Entry.objects.filter(thread=self.thread). \
            filter(created_at__gt=self.created_at).count()

    def get_previous(self):
        """ Get the previous entries count in the thread """
        return Entry.objects.filter(thread=self.thread). \
            filter(created_at__lt=self.created_at).count()

    def get_favorites(self):
        return self.favorites.all()

    def is_faved(self, user_id):
        if user_id in self.favorites.all():
            return True


class Favorite(models.Model):
    id = None
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='favorites')
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE,
                              related_name='favorites')

    class Meta:
        unique_together = ('user', 'entry')

# class Like(models.Model):
#     pass

app/entries/forms.py
import bleach

from django import forms

from .models import Entry


class EntryForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(
        attrs={'required': "true", 'cols': "75%", 'rows': "5",
               "id": "entryarea", "spellcheck": "false", "class": "textarea"}),
        max_length=50000, required=True, label='')

    class Meta:
        model = Entry
        fields = ['body']


class BodyForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'your ea', 'cols': "75%", 'rows': "5"}),
        max_length=50000, required=True, label='')

    def clean_body(self):
        data = self.cleaned_data['body'].lower()
        # r = bleach.clean(data, tags=['a'], attributes={}, styles=[])
        return data

app/entries/views.py
import json
import time

import bleach
from bleach.sanitizer import ALLOWED_TAGS, ALLOWED_ATTRIBUTES, ALLOWED_STYLES
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F, QuerySet
from django.http import Http404, HttpResponseNotFound, HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import get_language as lang
from django.utils.translation import ugettext as _
from django.views import generic

from .forms import EntryForm, BodyForm
from .models import Entry, Favorite
from ..threads.models import Thread


class EntryRead(generic.DetailView):
    model = Entry
    template_name = 'entries/read.html'

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        queryset = self.get_queryset().with_favs(self.request.user)\
            .annotate(username=F("user__username")).select_related("thread")
        try:
            entry = queryset.get(pk=pk)
        except ObjectDoesNotExist:
            entry = None
        return entry

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id'] = self.kwargs['pk']
        # context['tags'] = self.get_object().thread.tags.all
        return context


class EntryUpdate(generic.UpdateView):
    model = Entry
    template_name = 'entries/update.html'
    form_class = EntryForm

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if not obj.updated_at:
            obj.first_body = obj.body
            obj.save()

        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.body = bleach.clean(entry.body, tags=[])
        entry.updated_at = timezone.now()
        entry.save()
        messages.success(self.request, message=_("your entry was updated successfully"))
        return redirect('entry:read', pk=entry.pk)

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            messages.error(request, message=_("what a nice entry isn't it? if is not try to complain."))
            return redirect(obj.thread)
        return super(EntryUpdate, self).dispatch(request, *args, **kwargs)


class EntryDelete(generic.DeleteView):
    model = Entry
    context_object_name = 'entry'
    template_name = 'entries/confirm_delete.html'
    success_url = '/'

    def get_object(self, queryset=None):
        return self.entry

    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg)
        queryset = self.get_queryset().annotate(username=F("user__username")) \
            .select_related('thread')
        try:
            self.entry = queryset.get(id=pk)
        except ObjectDoesNotExist:
            return redirect("entry:read", pk)

        if self.entry.user_id != self.request.user.id:
            messages.error(request, _("this entry is not your. don't even try"))
            return redirect("entry:read", pk)
        return super(EntryDelete, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        thread = self.entry.thread
        self.entry.delete()
        messages.info(request, _("your entry was deleted successfully"))
        return redirect(thread)


@login_required
def add_entry(request, slug):
    thread = get_object_or_404(Thread, slug=slug)
    if thread.is_closed:
        messages.error(request, _("this thread is closed don't even try"))
        return redirect(thread)
    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.body = bleach.clean(entry.body, tags=[])
            entry.thread = thread
            entry.user = request.user  # auth.get_user(request)
            entry.lang = thread.lang   # lang() langs should be same as thread
            entry.created_at = timezone.now()  # removed auto_now_add for adm
            entry.save()

            thread.last_entry = timezone.now()
            thread.save()

            thread_url = reverse('thread:read', kwargs={'slug': slug})
            url = f'{thread_url}?page=last#{entry.id}'
            messages.success(request, _('your entry was published'))
            return redirect(url)
    return redirect(thread)


@login_required
def favorite_entry(request, pk):
    favorite, created = Favorite.objects\
        .get_or_create(user=request.user, entry=Entry.objects.get(id=pk))
    # time.sleep(0.1)
    if not created:
        favorite.delete()

    return HttpResponse(
        json.dumps({
            "result": created,
            "count": Favorite.objects.filter(entry_id=pk).count()
        }),
        content_type="application/json")

templates/entries/confirm_delete.html
{% extends "app/base.html" %}{% load i18n %}
{% block title %}
  {% trans "delete entry" %} - #{{ entry.id }}
{% endblock %}
{% block content %}
  <p class="title is-4">
    <a href="{{ entry.thread.get_absolute_url }}">{{ entry.thread.title }}</a>
  </p>
  {% include "app/entry.html" %}
  <div class="modal is-active is-clipped">
  <div class="modal-background"></div>
  <div class="modal-card">
    <div class="modal-card-head">
      <p class="has-text-light">{% trans "are you sure you want to delete this entry?" %}</p>
    </div>
    <div class="modal-card-body">
      <form method="post">
        {% csrf_token %}
        <div class="field">
          <div class="control">
{#            <a href="/">#}
{#              <button class="button is-danger is-outlined is-rounded" type="submit">#}
{#                {% trans "delete" %}#}
{#              </button>#}
{#            </a>#}
            <input class="button is-danger is-outlined is-rounded" type="submit" value="{% trans "delete" %}">
            <a class="button is-warning is-outlined is-rounded is-pulled-right"
               href="{% url "entry:read" entry.id %}">
                {% trans "cancel" %}
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/entries/read.html
{% extends "app/base.html" %}{% load i18n %}

{% block title %}
  {% if entry %}
    entry #{{ entry.id }} - {{ entry.thread.title }} -
  {% else %}
    {% trans "entry could not found" %} -
  {% endif %}
{% endblock %}

{% block content %}
  {% if entry %}
    <div name="thread" class="panel">
      <p class="title is-4">
        <a href="{{ entry.thread.get_absolute_url }}">{{ entry.thread.title }}</a>
      </p>
      <hr>
      {% with prev=entry.get_previous %}
        {% if prev != 0 %}
          <a href="{{ entry.thread.get_absolute_url }}">
            <button class="button is-fullwidth is-dark is-outlined has-text-light">
              {{ prev }} {% trans "more" %}
            </button>
          </a>
        {% endif %}
      {% endwith %}
      {% include "app/entry.html" %}
      {% with next=entry.get_next %}
        {% if next != 0 %}
          <a href="{{ entry.thread.get_absolute_url }}?page=last">
            <button class="button is-fullwidth is-dark has-text-light">
              {{ next }} {% trans "more" %}
            </button>
          </a>
        {% endif %}
      {% endwith %}
    </div>
  {% else %}
    <p class="subtitle">{% trans "entry could not found" %}</p>
    <p>{% blocktrans %}maybe entry #{{ id }} never existed. never and ever.{% endblocktrans %}</p>

  {% endif %}
{% endblock %}

{% block rightpane %}
  {% if entry %}
    <p class="subtitle">{% trans "thread's tags" %}</p>
    <div class="tags are-medium">
      {% for tag in entry.thread.tags.all %}
        <span class="tag is-primary">
        <a href="{% url "thread:tag-read" tag.slug %}" class="has-text-dark">
          #{{ tag.label }}
        </a>
      </span>
      {% empty %}
        <p>
          {% trans "this thread has not any tag" %}
        </p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

{% block script %}
  <script>
    $('.entry-content').readmore('destroy');
  </script>
{% endblock %}

templates/entries/update.html
{% extends "app/base.html" %}{% load i18n %}

{% block title %}
  {% if entry %}
    #{{ entry.id }} - {{ entry.thread.title }} -
  {% else %}
    {% trans "entry could not found" %} -
  {% endif %}
{% endblock %}

{% block content %}
  {% if entry %}
    <div name="thread" class="panel">
      <p class="title is-4">
        <a href="{{ entry.thread.get_absolute_url }}">{{ entry.thread.title }}</a>
      </p>
      <hr>
      {% if user.is_authenticated %}
        <form action="{% url "entry:update" entry.id %}" method="POST" id="ea">
          {% csrf_token %}
          <div class="field">
            <div class="control">
              <textarea name="body" class="textarea" id="entryarea" rows="5">{{ entry.body }}</textarea>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <button type="submit" class="button is-rounded is-primary is-outlined">{% trans "send" %}</button>
            </div>
          </div>
        </form>
        </div>
      {% else %}
        <p class="entry">{% trans "please" %}
          <a href="{% url 'user:login' %}?next={{ request.path }}" class="primary">{% trans "save" %}</a>
          {% trans "to write" %}
        </p>
      {% endif %}
  {% endif %}
{% endblock %}

{% block rightpane %}
  {% if entry %}
    <p class="subtitle">{% trans "thread's tags" %}</p>
    <div class="tags are-medium">
      {% for tag in entry.thread.tags.all %}
        <span class="tag is-primary">
        <a href="{% url "thread:tag-read" tag.slug %}" class="has-text-dark">
          #{{ tag.label }}
        </a>
      </span>
      {% empty %}
        <p>
          {% trans "this thread has not any tag" %}
        </p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}